# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/baris/codes/pc-segmentation/swig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/baris/codes/pc-segmentation/swig/build

# Include any dependencies generated for this target.
include CMakeFiles/save_pc.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/save_pc.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/save_pc.dir/flags.make

CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o: CMakeFiles/save_pc.dir/flags.make
CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o: /home/baris/codes/pc-segmentation/src/pcSavePython.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/baris/codes/pc-segmentation/swig/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o -c /home/baris/codes/pc-segmentation/src/pcSavePython.cpp

CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/baris/codes/pc-segmentation/src/pcSavePython.cpp > CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.i

CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/baris/codes/pc-segmentation/src/pcSavePython.cpp -o CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.s

CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.requires:
.PHONY : CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.requires

CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.provides: CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.requires
	$(MAKE) -f CMakeFiles/save_pc.dir/build.make CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.provides.build
.PHONY : CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.provides

CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.provides.build: CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o

CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o: CMakeFiles/save_pc.dir/flags.make
CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o: ../pcSavePython_wrap.cxx
	$(CMAKE_COMMAND) -E cmake_progress_report /home/baris/codes/pc-segmentation/swig/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o -c /home/baris/codes/pc-segmentation/swig/pcSavePython_wrap.cxx

CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/baris/codes/pc-segmentation/swig/pcSavePython_wrap.cxx > CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.i

CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/baris/codes/pc-segmentation/swig/pcSavePython_wrap.cxx -o CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.s

CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.requires:
.PHONY : CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.requires

CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.provides: CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.requires
	$(MAKE) -f CMakeFiles/save_pc.dir/build.make CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.provides.build
.PHONY : CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.provides

CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.provides.build: CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o

# Object files for target save_pc
save_pc_OBJECTS = \
"CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o" \
"CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o"

# External object files for target save_pc
save_pc_EXTERNAL_OBJECTS =

libsave_pc.so: CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o
libsave_pc.so: CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o
libsave_pc.so: /home/baris/codes/pc-segmentation/build/libpcseg.so
libsave_pc.so: /usr/lib/libboost_system-mt.so
libsave_pc.so: /usr/lib/libboost_filesystem-mt.so
libsave_pc.so: /usr/lib/libboost_thread-mt.so
libsave_pc.so: /usr/lib/libboost_date_time-mt.so
libsave_pc.so: /usr/lib/libboost_iostreams-mt.so
libsave_pc.so: /usr/lib/libboost_mpi-mt.so
libsave_pc.so: /usr/lib/libboost_serialization-mt.so
libsave_pc.so: /usr/local/lib/libpcl_common.so
libsave_pc.so: /usr/local/lib/libpcl_octree.so
libsave_pc.so: /opt/ros/groovy/lib/libflann_cpp_s.a
libsave_pc.so: /usr/local/lib/libpcl_kdtree.so
libsave_pc.so: /usr/local/lib/libpcl_search.so
libsave_pc.so: /usr/local/lib/libpcl_sample_consensus.so
libsave_pc.so: /usr/local/lib/libpcl_filters.so
libsave_pc.so: /usr/lib/libOpenNI.so
libsave_pc.so: /usr/lib/libvtkCommon.so.5.8.0
libsave_pc.so: /usr/lib/libvtkRendering.so.5.8.0
libsave_pc.so: /usr/lib/libvtkHybrid.so.5.8.0
libsave_pc.so: /usr/lib/libvtkCharts.so.5.8.0
libsave_pc.so: /usr/local/lib/libpcl_io.so
libsave_pc.so: /usr/local/lib/libpcl_features.so
libsave_pc.so: /usr/local/lib/libpcl_registration.so
libsave_pc.so: /usr/local/lib/libpcl_ml.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_sample_consensus.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_features.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_segmentation.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_io.so
libsave_pc.so: /usr/local/lib/libpcl_segmentation.so
libsave_pc.so: /usr/lib/libqhull.so
libsave_pc.so: /usr/local/lib/libpcl_surface.so
libsave_pc.so: /usr/local/lib/libpcl_recognition.so
libsave_pc.so: /usr/local/lib/libpcl_keypoints.so
libsave_pc.so: /usr/local/lib/libpcl_visualization.so
libsave_pc.so: /usr/local/lib/libpcl_people.so
libsave_pc.so: /usr/local/lib/libpcl_outofcore.so
libsave_pc.so: /usr/local/lib/libpcl_tracking.so
libsave_pc.so: /usr/local/lib/libpcl_stereo.so
libsave_pc.so: /usr/lib/libboost_system-mt.so
libsave_pc.so: /usr/lib/libboost_filesystem-mt.so
libsave_pc.so: /usr/lib/libboost_thread-mt.so
libsave_pc.so: /usr/lib/libboost_date_time-mt.so
libsave_pc.so: /usr/lib/libboost_iostreams-mt.so
libsave_pc.so: /usr/lib/libboost_mpi-mt.so
libsave_pc.so: /usr/lib/libboost_serialization-mt.so
libsave_pc.so: /usr/lib/libqhull.so
libsave_pc.so: /usr/lib/libOpenNI.so
libsave_pc.so: /opt/ros/groovy/lib/libflann_cpp_s.a
libsave_pc.so: /usr/lib/libvtkCommon.so.5.8.0
libsave_pc.so: /usr/lib/libvtkRendering.so.5.8.0
libsave_pc.so: /usr/lib/libvtkHybrid.so.5.8.0
libsave_pc.so: /usr/lib/libvtkCharts.so.5.8.0
libsave_pc.so: /opt/ros/groovy/lib/libroscpp.so
libsave_pc.so: /opt/ros/groovy/lib/libroscpp_serialization.so
libsave_pc.so: /opt/ros/groovy/lib/librosconsole.so
libsave_pc.so: /opt/ros/groovy/lib/libroslib.so
libsave_pc.so: /usr/local/lib/libpcl_common.so
libsave_pc.so: /usr/local/lib/libpcl_octree.so
libsave_pc.so: /usr/local/lib/libpcl_kdtree.so
libsave_pc.so: /usr/local/lib/libpcl_search.so
libsave_pc.so: /usr/local/lib/libpcl_sample_consensus.so
libsave_pc.so: /usr/local/lib/libpcl_filters.so
libsave_pc.so: /usr/local/lib/libpcl_io.so
libsave_pc.so: /usr/local/lib/libpcl_features.so
libsave_pc.so: /usr/local/lib/libpcl_registration.so
libsave_pc.so: /usr/local/lib/libpcl_ml.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_sample_consensus.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_features.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_segmentation.so
libsave_pc.so: /usr/local/lib/libpcl_cuda_io.so
libsave_pc.so: /usr/local/lib/libpcl_segmentation.so
libsave_pc.so: /usr/local/lib/libpcl_surface.so
libsave_pc.so: /usr/local/lib/libpcl_recognition.so
libsave_pc.so: /usr/local/lib/libpcl_keypoints.so
libsave_pc.so: /usr/local/lib/libpcl_visualization.so
libsave_pc.so: /usr/local/lib/libpcl_people.so
libsave_pc.so: /usr/local/lib/libpcl_outofcore.so
libsave_pc.so: /usr/local/lib/libpcl_tracking.so
libsave_pc.so: /usr/local/lib/libpcl_stereo.so
libsave_pc.so: /opt/ros/groovy/lib/libroscpp.so
libsave_pc.so: /opt/ros/groovy/lib/libroscpp_serialization.so
libsave_pc.so: /opt/ros/groovy/lib/librosconsole.so
libsave_pc.so: /opt/ros/groovy/lib/libroslib.so
libsave_pc.so: /usr/lib/libvtkViews.so.5.8.0
libsave_pc.so: /usr/lib/libvtkInfovis.so.5.8.0
libsave_pc.so: /usr/lib/libvtkWidgets.so.5.8.0
libsave_pc.so: /usr/lib/libvtkHybrid.so.5.8.0
libsave_pc.so: /usr/lib/libvtkParallel.so.5.8.0
libsave_pc.so: /usr/lib/libvtkVolumeRendering.so.5.8.0
libsave_pc.so: /usr/lib/libvtkRendering.so.5.8.0
libsave_pc.so: /usr/lib/libvtkGraphics.so.5.8.0
libsave_pc.so: /usr/lib/libvtkImaging.so.5.8.0
libsave_pc.so: /usr/lib/libvtkIO.so.5.8.0
libsave_pc.so: /usr/lib/libvtkFiltering.so.5.8.0
libsave_pc.so: /usr/lib/libvtkCommon.so.5.8.0
libsave_pc.so: /usr/lib/libvtksys.so.5.8.0
libsave_pc.so: CMakeFiles/save_pc.dir/build.make
libsave_pc.so: CMakeFiles/save_pc.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX shared library libsave_pc.so"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/save_pc.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/save_pc.dir/build: libsave_pc.so
.PHONY : CMakeFiles/save_pc.dir/build

CMakeFiles/save_pc.dir/requires: CMakeFiles/save_pc.dir/home/baris/codes/pc-segmentation/src/pcSavePython.cpp.o.requires
CMakeFiles/save_pc.dir/requires: CMakeFiles/save_pc.dir/pcSavePython_wrap.cxx.o.requires
.PHONY : CMakeFiles/save_pc.dir/requires

CMakeFiles/save_pc.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/save_pc.dir/cmake_clean.cmake
.PHONY : CMakeFiles/save_pc.dir/clean

CMakeFiles/save_pc.dir/depend:
	cd /home/baris/codes/pc-segmentation/swig/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/baris/codes/pc-segmentation/swig /home/baris/codes/pc-segmentation/swig /home/baris/codes/pc-segmentation/swig/build /home/baris/codes/pc-segmentation/swig/build /home/baris/codes/pc-segmentation/swig/build/CMakeFiles/save_pc.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/save_pc.dir/depend

